### ISSUE TITLE
【本地运行】uvicorn 报错

### ISSUE THREAD

**Issue by QwindF** [Kyomotoi/ATRI#100]
**描述错误 | Describe the bug**
uvicorn 报错

**如何复现 | To Reproduce**
告诉我们该错误是如何触发的:
1. 下载发布文件
2. 设置虚拟环境
3. 安装依赖
4. 运行报错

**日志 | Log**
```python
ATRI | 07-24 10:19:04 | SUCCESS nonebot >> Succeeded to load plugin "anime_search" from "ATRI.plugins.anime_search"
ATRI | 07-24 10:19:07 | SUCCESS nonebot >> Running NoneBot...
ATRI | 07-24 10:19:07 | INFO uvicorn >> Started server process [7000]
ATRI | 07-24 10:19:07 | INFO uvicorn >> Waiting for application startup.
ATRI | 07-24 10:19:12 | WARNING twitter >> 无法连接至 Twitter，这将导致相关插件无法工作. 已自动禁用.
ATRI | 07-24 10:19:12 | SUCCESS anti_effort >> 插件 anti_effort 装载资源完成
ATRI | 07-24 10:19:12 | SUCCESS polaroid >> 插件 polaroid 装载资源完成
ATRI | 07-24 10:19:12 | INFO ATRI >> 正在初始化数据库...
ATRI | 07-24 10:19:12 | SUCCESS ATRI >> 数据库初始化完成
ATRI | 07-24 10:19:12 | INFO essential >> Now running: YHN-001-A07
ATRI | 07-24 10:19:12 | INFO essential >> Starting to check update...
ATRI | 07-24 10:19:13 | INFO essential >> Latest commit 🔀 Merge pull request #94 from KomoriDev/main

Plugin: 删除 `console` 插件 | sha: 1a4c9 | time: 2023-10-08T03:17:28Z
ATRI | 07-24 10:19:14 | INFO essential >> Scheduler Started.
ATRI | 07-24 10:19:14 | INFO essential >> アトリは、高性能ですから！
ATRI | 07-24 10:19:14 | ERROR uvicorn >> Traceback (most recent call last):
  File "D:\BOT\ATRI-YHN-001-A07\venv\lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "D:\BOT\ATRI-YHN-001-A07\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\BOT\ATRI-YHN-001-A07\venv\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\BOT\ATRI-YHN-001-A07\venv\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 38, in _run_lifespan_func
    await run_sync(cast(SYNC_LIFESPAN_FUNC, func))()
  File "D:\BOT\ATRI-YHN-001-A07\venv\lib\site-packages\nonebot\utils.py", line 182, in _wrapper
    result = await loop.run_in_executor(None, partial(context.run, pfunc))
  File "D:\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\BOT\ATRI-YHN-001-A07\ATRI\plugins\console\driver\__init__.py", line 56, in init
    register_routes(driver())  # type: ignore
  File "D:\BOT\ATRI-YHN-001-A07\ATRI\plugins\console\driver\__init__.py", line 33, in register_routes
    app.add_middleware(
  File "D:\BOT\ATRI-YHN-001-A07\venv\lib\site-packages\starlette\applications.py", line 141, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started

ATRI | 07-24 10:19:14 | ERROR uvicorn >> Application startup failed. Exiting.
```

**操作环境 | Desktop:**
 - OS: Windows 11 
 - python: 3.9.9
 - Platform Info: 12c32g
 - ATRI Version: YHN-001-A07
 - Runtime Area: CN

**Comment by Kyomotoi** [comment]
🐦🐦🐦

别下 Release 的，直接 clone master。
