### ISSUE TITLE
部署时出错

### ISSUE THREAD

**Issue by zjuatri** [Kyomotoi/ATRI#103]
11-21 19:21:27 [SUCCESS] nonebot | NoneBot is initializing...
11-21 19:21:27 [INFO] nonebot | Current Env: prod
ATRI | 11-21 19:21:27 | SUCCESS nonebot >> Succeeded to load plugin "polaroid" from "ATRI.plugins.polaroid"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "kimo" from "ATRI.plugins.kimo"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "rss" from "ATRI.plugins.rss"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "status" from "ATRI.plugins.status"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "broadcast" from "ATRI.plugins.broadcast"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "geoip" from "ATRI.plugins.geoip"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "repo" from "ATRI.plugins.repo"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "setu" from "ATRI.plugins.setu"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "code_runner" from "ATRI.plugins.code_runner"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "applet" from "ATRI.plugins.applet"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "thesaurus" from "ATRI.plugins.thesaurus"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "anime_search" from "ATRI.plugins.anime_search"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "anti_effort" from "ATRI.plugins.anti_effort"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "util" from "ATRI.plugins.util"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "bilibili_dynamic" from "ATRI.plugins.bilibili_dynamic"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "help" from "ATRI.plugins.help"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "twitter" from "ATRI.plugins.twitter"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "manage" from "ATRI.plugins.manage"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "funny" from "ATRI.plugins.funny"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "saucenao" from "ATRI.plugins.saucenao"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "auto_tietie" from "ATRI.plugins.auto_tietie"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "essential" from "ATRI.plugins.essential"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "rss_rsshub" from "ATRI.plugins.rss.rss_rsshub"
ATRI | 11-21 19:21:28 | SUCCESS nonebot >> Succeeded to load plugin "rss_mikanan" from "ATRI.plugins.rss.rss_mikanan"
ATRI | 11-21 19:21:30 | SUCCESS nonebot >> Succeeded to load plugin "nonebot_plugin_gocqhttp"
ATRI | 11-21 19:21:33 | SUCCESS nonebot >> Running NoneBot...
ATRI | 11-21 19:21:33 | INFO ATRI >> 正在初始化数据库...
ATRI | 11-21 19:21:33 | SUCCESS ATRI >> 数据库初始化完成
ATRI | 11-21 19:21:33 | INFO ATRI >> 当前版本: YHN-001-A07
ATRI | 11-21 19:21:33 | INFO ATRI >> 开始检查更新...
ATRI | 11-21 19:21:33 | INFO ATRI >> Latest commit 🔀 Merge pull request #94 from KomoriDev/main

Plugin: 删除 `console` 插件 | sha: 1a4c9 | time: 2023-10-08T03:17:28Z
ATRI | 11-21 19:21:34 | INFO ATRI >> 定时任务已启用
ATRI | 11-21 19:21:34 | INFO ATRI >> アトリは、高性能ですから！
ATRI | 11-21 19:21:34 | SUCCESS polaroid >> 插件 polaroid 装载资源完成
ATRI | 11-21 19:21:34 | WARNING geoip >> 插件 IP查询 所需的设置未配置, 将被全局禁用, 填写后请手动启用
ATRI | 11-21 19:21:34 | SUCCESS setu >> 插件 setu 装载资源完成
ATRI | 11-21 19:21:34 | SUCCESS anti_effort >> 插件 anti_effort 装载资源完成
ATRI | 11-21 19:21:34 | SUCCESS twitter >> 已成功连接: Twitter
ATRI | 11-21 19:21:35 | SUCCESS manage >> 刷新 Nonebot 商店成功
ATRI | 11-21 19:21:37 | ERROR gocqhttp >> An error has been caught in function 'startup', process 'MainProcess' (905456), thread 'MainThread' (139771460248000):
Traceback (most recent call last):

  File "/root/ATRI/main.py", line 9, in <module>
    ATRI.run()
    │    └ <function run at 0x7f1f11c0a320>
    └ <module 'ATRI' from '/root/ATRI/ATRI/__init__.py'>

  File "/root/ATRI/ATRI/__init__.py", line 36, in run
    nonebot.run(log_level=log_level)
    │       │             └ 'warning'
    │       └ <function run at 0x7f1f1292dea0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/__init__....

  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'log_level': 'warning'}
    │                 └ ()
    └ <function get_driver at 0x7f1f1292e320>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
    │       └ <function run at 0x7f1f11b6a5f0>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/uvicorn/__init__....
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7f1f11b6a7a0>
    └ <uvicorn.server.Server object at 0x7f1eecb540a0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f1f11b6a830>
           │       │   └ <uvicorn.server.Server object at 0x7f1eecb540a0>
           │       └ <function run at 0x7f1f13aaf6d0>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f1f1172c2e0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 88, in main
    await app(scope, self.receive, self.send)
          │   │      │    │        │    └ <function LifespanOn.send at 0x7f1eec871990>
          │   │      │    │        └ <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>
          │   │      │    └ <function LifespanOn.receive at 0x7f1eec871a20>
          │   │      └ <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>
          │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f1eec7f24d0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
                 │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
                 │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
                 │    └ <fastapi.applications.FastAPI object at 0x7f1f11713880>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f1eec7f24d0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
                           │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
                           └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │                │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │                └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f1eec85da80>
          └ <fastapi.applications.FastAPI object at 0x7f1f11713880>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f1eec85dab0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f1eec85da80>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 55, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f1eec85db10>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f1eec85dab0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.routing.APIRouter object at 0x7f1f117138e0>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f1eec85db10>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 707, in __call__
    await self.lifespan(scope, receive, send)
          │    │        │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │        │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7f1eecb54700>>
          │    │        └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <function Router.lifespan at 0x7f1f118ef9a0>
          └ <fastapi.routing.APIRouter object at 0x7f1f117138e0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               │    │                └ <fastapi.applications.FastAPI object at 0x7f1f11713880>
               │    └ <bound method Driver._lifespan_manager of Driver(type='fastapi', adapters=1, bots=0)>
               └ <fastapi.routing.APIRouter object at 0x7f1f117138e0>
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
                       │    └ <async_generator object Driver._lifespan_manager at 0x7f1eec84cdc0>
                       └ <contextlib._AsyncGeneratorContextManager object at 0x7f1eec85dc00>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
          │    │         └ <function Lifespan.startup at 0x7f1f11c7d120>
          │    └ <nonebot.drivers._lifespan.Lifespan object at 0x7f1f13ee6cb0>
          └ Driver(type='fastapi', adapters=1, bots=0)
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
          │    │                  │    └ [<function startup at 0x7f1f100b5870>, <function init_source at 0x7f1f0aa9d630>, <function _check_need at 0x7f1efee2b910>, <f...
          │    │                  └ <nonebot.drivers._lifespan.Lifespan object at 0x7f1f13ee6cb0>
          │    └ <staticmethod(<function Lifespan._run_lifespan_func at 0x7f1f11c7d090>)>
          └ <nonebot.drivers._lifespan.Lifespan object at 0x7f1f13ee6cb0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
          │    │                    └ <function startup at 0x7f1eecd54af0>
          │    └ typing.Callable[[], typing.Awaitable[typing.Any]]
          └ <function cast at 0x7f1f13b37400>
> File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 40, in startup
    await download_gocq()
          └ <function download_gocq at 0x7f1eecbbdab0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot_plugin_gocqhttp/process/download.py", line 107, in download_gocq
    url = await get_fastest_mirror(client)
                │                  └ <httpx.AsyncClient object at 0x7f1eec8c5930>
                └ <function get_fastest_mirror at 0x7f1eecd557e0>
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot_plugin_gocqhttp/process/download.py", line 91, in get_fastest_mirror
    assert lowest_latency and fastest_url, "No download domain available."
           │                  └ None
           └ None

AssertionError: No download domain available.
ATRI | 11-21 19:21:37 | ERROR uvicorn >> Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot/drivers/_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 40, in startup
    await download_gocq()
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/loguru/_logger.py", line 1212, in catch_wrapper
    return await function(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot_plugin_gocqhttp/process/download.py", line 107, in download_gocq
    url = await get_fastest_mirror(client)
  File "/root/.cache/pypoetry/virtualenvs/atri-DD5MxRQ5-py3.10/lib/python3.10/site-packages/nonebot_plugin_gocqhttp/process/download.py", line 91, in get_fastest_mirror
    assert lowest_latency and fastest_url, "No download domain available."
AssertionError: No download domain available.

ATRI | 11-21 19:21:37 | ERROR uvicorn >> Application startup failed. Exiting.

**Comment by zjuatri** [comment]
download domain按照文档换了一圈了也没用（挠头），不知道该怎么改，请开发者不吝赐教

**Comment by Kyomotoi** [comment]
设置里把gocqhttp的 **enabled** 改为 `false`，然后换用其他机器人实现
