### ISSUE TITLE
docker启动报错

### ISSUE THREAD

**Issue by rubyangxg** [Kyomotoi/ATRI#50]
```
nonebot  | ATRI | 04-01 05:22:08 | INFO uvicorn >> Waiting for application startup.
nonebot  | ATRI | 04-01 05:22:08 | ERROR uvicorn >> Traceback (most recent call last):
nonebot  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 621, in lifespan
nonebot  |     async with self.lifespan_context(app):
nonebot  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 518, in __aenter__
nonebot  |     await self._router.startup()
nonebot  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 598, in startup
nonebot  |     await handler()
nonebot  |   File "/app/ATRI/utils/apscheduler.py", line 22, in _start_scheduler
nonebot  |     scheduler.start()
nonebot  |   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/asyncio.py", line 45, in start
nonebot  |     super(AsyncIOScheduler, self).start(paused)
nonebot  |   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 167, in start
nonebot  |     self._real_add_job(job, jobstore_alias, replace_existing)
nonebot  |   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 863, in _real_add_job
nonebot  |     replacements['next_run_time'] = job.trigger.get_next_fire_time(None, now)
nonebot  |   File "/usr/local/lib/python3.9/site-packages/apscheduler/triggers/combining.py", line 55, in get_next_fire_time
nonebot  |     fire_times = [trigger.get_next_fire_time(previous_fire_time, now)
nonebot  |   File "/usr/local/lib/python3.9/site-packages/apscheduler/triggers/combining.py", line 55, in <listcomp>
nonebot  |     fire_times = [trigger.get_next_fire_time(previous_fire_time, now)
nonebot  | TypeError: get_next_fire_time() takes 2 positional arguments but 3 were given
nonebot  | 
nonebot  | ATRI | 04-01 05:22:08 | ERROR uvicorn >> Application startup failed. Exiting.
nonebot exited with code 3
```

**Comment by Kyomotoi** [comment]
请尝试将依赖 `apscheduler` 回退至前几个版本

**Comment by Kyomotoi** [comment]
已大致了解概况，大概率是 `python新版本的特性`，我本地的环境是 `python3.8.5`，你可以先安排此版本或等后续修复

**Comment by Kyomotoi** [comment]
最新的pull已修复，请重新 clone 并替换 config.yml, data 即可
