### ISSUE TITLE
没有打开“使用内置gocqhttp”导致的参数问题

### ISSUE THREAD

**Issue by SoulGI** [Kyomotoi/ATRI#87]
**描述问题 | Describe the question**
请尽可能地使用简洁语言描述，以方便开发者快速定位重点.
进入虚拟环境运行python main.py报错如下
--------------------------------------------------------
(atri-py3.8) ubuntu@VM-8-10-ubuntu:~/ATRI$ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import ATRI
  File "/home/ubuntu/ATRI/ATRI/__init__.py", line 13, in <module>
    conf = __conf.parse()
  File "/home/ubuntu/ATRI/ATRI/configs/config.py", line 38, in parse
    return ConfigModel.parse_obj(self.config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ConfigModel
WithGoCQHTTP -> accounts -> 0 -> uin
  value is not a valid integer (type=type_error.integer)
WithGoCQHTTP -> accounts -> 0 -> protocol
  value is not a valid integer (type=type_error.integer)
-----------------------------------------------------------
疑似是因为我没有打开“使用内置gocqhttp”导致的参数问题
（把花括号去了然后装模做样输点数据就能跑了）
这算不算bug（）

**补充内容 | Additional context**
你可以在此添加其它说明.

**Comment by Kyomotoi** [comment]
应该算 model 设计的不严谨，后续会推送更新以规避此类报错）
