### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by huajidawang666** [Kyomotoi/ATRI#96]
**描述问题 | Describe the question**
按照文档部署，运行`python main.py`时导入报错

**补充内容 | Additional context**
log:
```
z****u@homeserver:~/ATRI$ poetry shell
Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source tsinghua-mirror. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
Spawning shell within /home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10
z****u@homeserver:~/ATRI$ . /home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/bin/activate
(atri-py3.10) z****u@homeserver:~/ATRI$ python main.py
Traceback (most recent call last):
  File "/home/z****u/ATRI/main.py", line 3, in <module>
    import ATRI
  File "/home/z****u/ATRI/ATRI/__init__.py", line 4, in <module>
    import nonebot
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 140, in <module>
    from .command import CommandSession, CommandGroup
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/command/__init__.py", line 930, in <module>
    from nonebot.command.group import CommandGroup
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/command/group.py", line 3, in <module>
    from nonebot.plugin import on_command
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/plugin/__init__.py", line 109, in <module>
    from .on import on as on
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/plugin/on.py", line 13, in <module>
    from nonebot.adapters import Event
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/adapters/__init__.py", line 10, in <module>
    from nonebot.internal.adapter import Bot as Bot
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/internal/adapter/__init__.py", line 1, in <module>
    from .bot import Bot as Bot
  File "/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 9, in <module>
    from nonebot.typing import T_CalledAPIHook, T_CallingAPIHook
ImportError: cannot import name 'T_CalledAPIHook' from 'nonebot.typing' (/home/z****u/.cache/pypoetry/virtualenvs/atri-KwwySn6q-py3.10/lib/python3.10/site-packages/nonebot/typing.py)
(atri-py3.10) z****u@homeserver:~/ATRI$ 
```
*易被盒注释掉了用户名*

**Comment by Kyomotoi** [comment]
nonebot2 的版本是？
